CONVERSATION_REWRITER_USER_PROMPT = (
    "Role: rewriter\n"
    "Task: Rewrite the conversation among system, student_alpha, student_beta, and teacher.\n\n"
    "Instructions:\n"
    "1. Remove any meaningless, repetitive, or irrelevant content from the conversation.\n"
    "2. Improve the coherence and interactivity of the conversation.\n"
    "3. Keep the original reasoning processes and thought patterns fully intact.\n"
    "4. Preserve the original order of messages, role tags, and speaker tone.\n"
    "5. Do not introduce any information that goes beyond the original conversation.\n"
    "6. Ensure the entire conversation is written in English only.\n"
    "7. Output the rewritten conversation within a bash code block, formatted as: ```bash ... ```.\n\n"
    "REWRITE THE CONVERSATION NOW."
)
LONGCOT_REWRITER_USER_PROMPT = (
    "Role: rewriter\n"
    "Task: Rewrite the conversation involving multiple participants into a single long chain of thought.\n\n"
    "Instructions:\n"
    "1. Preserve all original reasoning processes and thought patterns without distortion.\n"
    "2. Do not introduce any information that goes beyond the original conversation.\n"
    "3. Remove any meaningless, repetitive, or irrelevant content.\n"
    "4. Improve the coherence and logical flow of the reasoning.\n"
    "5. Rewrite everything in the first-person point of view, as a continuous inner monologue.\n"
    "6. Do not include any role tags or speaker identifiers.\n"
    "7. Ensure the entire output is written in English only.\n"
    "8. Output the rewritten long chain of thought inside a markdown code block, formatted as: ```markdown ... ```.\n\n"
    "REWRITE THE CONVERSATION INTO A LONG CHAIN OF THOUGHT NOW."
)
